
style = "sciml"

# # scope
# format_docstrings = true
# format_markdown = true
# ignore = ["LICENSE.md", "README.md"]

# ## additional options that do not violate the sciml style

# # use whitespaces
# indent_submodule = true
# align_matrix = true

# # modify code in these additional cases
# import_to_using = true
# short_to_long_function_def = true
# conditional_to_if = true
# long_to_short_function_def = true
# separate_kwargs_with_semicolon = true
# always_use_return = true
